version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Pr1sm4_Pr1sm4'
      ACCEPT_EULA: 'Y'
    volumes:
      - mssql:/var/opt/mssql
volumes:
  mssql: